export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJyaWNhcmRvQGdtYWlsLmNvbSIsIm5hbWUiOiJSaWNhcmRvIEFtYXJhbCIsImlhdCI6MTcxMDE5MDI5NSwiZXhwIjoxNzEwNzk1MDk1LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiOSJ9.po8V3m0vK3VEODkhZHf0Upd-UEhXDPxFlWbhOO7nKa4';
